### ISSUE TITLE
Crash upon extraction

### ISSUE THREAD

**Issue by Notselwyn** [jancc/vma-extractor#2]

**Comment by jancc** [comment]
Hmm yeah, I basically skipped the part where I'd have to do any sanity checking or error handling on the input data 😅
In this case it seems that a chunk references a device that has not been listed in the VMA's header. Handling this case should be simple, as I could just open additional file objects when such a case is encountered.

Just out of interest: Has this happened with an "actual" VMA produced by a production Proxmox instance? Because the path implies that this was part of a CTF, so the file may have been intentionally messed with ^^

**Comment by Notselwyn** [comment]
Yeah, it was messed with and it was part of a CTF indeed. It hinted that there was a part of the disk that was hidden so I was already questioning if this extraction tool could do it (I probably should've said that). 

Nevertheless I fixed it by hardcoding a `1` key into device_fos.
